title: ADBC Driver Foundry
description: >-
  An open source hub for federated ADBC driver development
url: "https://adbc-drivers.org"
github_username: adbc-drivers
logo: /assets/images/adbc-drivers-logo.png
image: /assets/images/adbc-drivers-logo.png
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
